### PR TITLE
Fix a typo in the English string table

### PR DESCRIPTION
**Pull request by FlorianLoch**
Just a fix for two typos I noticed. Actually, I spotted one and then found the second one when checking the whole file.

### CODE REVIEW

**Comment by FlorianLoch** [comment]
Any feedback on this? ;)

**Comment by jp112sdl** [comment]
@FlorianLoch 
Have a look at the other open PRs and Issues over the last few years and count the number of eQ-3 replies.

I think, this repository is just a versioned file storage to publish the OCCU project

**Comment by jens-maus** [comment]
Isn't this why RaspberryMatic and its WebUI patchsets exist? Thus, I just added the findings from @FlorianLoch to the `0143-WebUI-Fix-Translation` WebUI patchset in https://github.com/jens-maus/RaspberryMatic/commit/71a732042b74b5f8e9f7a3ca9aaa640874f62c77 so that at least in RaspberryMatic it will be fixed with the next upcoming release. Thanks @FlorianLoch. And next time submit your findings directly to the RaspberryMatic I would suggest :)

**Comment by FlorianLoch** [comment]
Now that @jp112sdl mentions it - yes, seems like it.

I wasn't aware of how the projects relate exactly... Now I do ;)

Thank @jens-maus

**Pull request closed without merging**
